### ISSUE TITLE
Real phone!?

### ISSUE THREAD

**Issue by Dancopy** [elementzonline/Arduino-Sample-Codes#2]
It is not an issue but a question.
How to make a real phone with this sketch: phonecal.ino
Thanks

**Comment by elementzonline** [comment]
You need to connect a GSM Modem with Arduino. Arduino should be connected to an LCD display to show the phone numbers. This will be a fun project to do!

**Comment by Dancopy** [comment]
OK! Do you know any projects ready for this or do you intend to do it?
It would be nice with a larger screen like ILI9488 3.5 inch. Thanks

**Comment by elementzonline** [comment]
You can search Arduino forums, and probably ask. Thanks
